apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway-private-mgcp
  servers:
  - hosts:
    - {{ .Values.host }}
    port:
      name: http
      protocol: HTTP
      number: 443
